### ISSUE TITLE
Sokağa çıkma yasağı başlangıcı

### ISSUE THREAD

**Issue by StZiza** [ozanerturk/canigoout#1]
Siteye girildiğinde 20 - 65 yaş arası grup için cuma saat 20'den itibaren sokağa çıkma yasağı olduğu söylüyor ancak genelgelere göre sokağa çıkma yasağı cumartesi günleri 20'de başlıyor. Cuma günü değil.

**Comment by ozanerturk** [comment]
Resmi genelge linkini paylaşabilir misiniz ? Referans olmuş olur.

**Comment by ozanerturk** [comment]
Şimdi bi fix geçtim düzelmiş olması gerekiyor.

**Comment by StZiza** [comment]
Ok. Düzelmiş. Geç gördüğüm için genelge atamadım. İl Hıfsızsıhha sayfalarında yazıyor.
