### ISSUE TITLE
Cuma Namazı

### ISSUE THREAD

**Issue by Ardelon** [ozanerturk/canigoout#2]
20 kasım cuma günü gelen haberlere göre cuma namazı eğer kısıtlama varsa bun kısıtlamanın dışında kalacakmış. Eğer algoritmada buna uygun bir madde eklemek gerekiyorsa lütfen ekleyin.

**Comment by ozanerturk** [comment]
Resmi genelge linkini paylaşabilir misiniz ? Referans olmuş olur.
